# Load numpy

In [4]:
import numpy as np

# The basics

In [5]:
a = np.array([1, 2, 3], dtype="int64")
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# get dimension
a.ndim

1

In [8]:
b.ndim

2

In [9]:
# get shape
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
# get type
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('float64')

In [13]:
# get size
a.itemsize

8

In [14]:
b.itemsize

8

In [15]:
# get total size
a.nbytes

24

In [16]:
b.nbytes

48

In [17]:
# get number of elements
a.size

3

In [18]:
b.size

6

#  Accessing / changing specific elements, rows, columns, etc

In [19]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# get specific element [r, c]
a[1,5]

13

In [21]:
# get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# get specific column
a[:, 2]

array([ 3, 10])

In [24]:
# get little more fancy [startindix:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [26]:
a[1, 5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [27]:
b = np.array([[1,2], [3,4], [5,6], [7,8]])
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
# get specific element (work outside in)
b[0,1,1]

4

In [40]:
# replace
b[:, 1, :] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [38]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# initializing different types if array

In [41]:
# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# all 1st matrix
np.ones((4,2,2), dtype="int64")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int64)

In [43]:
# any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [46]:
# any other number (full_like)
np.full_like(b, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [47]:
# any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [45]:
# random decimal number
np.random.rand(4, 2)

array([[0.23658883, 0.84707946],
       [0.76999755, 0.63370264],
       [0.14062733, 0.38632237],
       [0.52338659, 0.67988381]])

In [48]:
# random integer values
np.random.randint(-4, 8, size=(3,3))

array([[-1,  1,  3],
       [ 7,  1, -3],
       [ 4,  4,  7]])

In [49]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
# repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [53]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
a = np.array([1,2,3])
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


# Mathematics

In [76]:
a = np.array([1,2,3, 4])
print(a)

[1 2 3 4]


In [77]:
a + 2

array([3, 4, 5, 6])

In [70]:
a - 2

array([-1,  0,  1])

In [78]:
a * 2

array([2, 4, 6, 8])

In [79]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [81]:
b = np.array([1,0,1,0])
print(b)
a + b

[1 0 1 0]


array([2, 2, 4, 4])

In [82]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [83]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [84]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# lineat algebra

In [89]:
a = np.ones((2,3))
print(a)

b= np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [94]:
# find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [95]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.min(stats)

1

In [98]:
np.max(stats)
np.max(stats, axis=1)

array([3, 6])

In [100]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [104]:
# Reorganizing array
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [105]:
after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


In [106]:
# vertically stacking vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.stack((v1, v2, v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
# Horizontal stack
h1 = np.ones((2,3))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

# Miscellaneous

In [132]:
filedata = np.genfromtxt("file_data.txt", delimiter=",")
filedata = filedata.astype("int64")
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [134]:
# Boolean masking and advanced indexing
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])